name = input('OLA! My name is MAC, the MAChine. What´s yours? ').strip()
input('That´s a very nice name, {}. Would you like to play a game with me, {}? '.format(name, name))
print('A QUIZ!')
input('I´ll make you questions and if you answer correctly I´ll reply as "True" and if you don´t then I´ll simply reply with a "False". Did you get it? ')
print('HA HA HA')
input('Let´s have some fun!')
print()
print('First question:')
first = str(input('In which country was Leonardo da Vinci born? ')).strip()
print('ITALY' in first.upper())
input('Correct answer: Italy')
print()
print('Second question:')
second = str(input('What are the first 3 digits of the number of PI? '))
print('3,14' in second.upper())
input('Correct answer: 3,14')
print()
print('Third question:')
third = str(input('What was the first name to go to space? '))
print('LAIKA' in third.upper())
print('Correct answer: Laika, the dog')
print()
print('Fourth question: ')
input('Do computers have a sense of humor?')
input('I´m not funny to you?')
print('Just kidding')
print('HA HA HA')
input()
fourth = str(input('What´s the greatest intelligence on earth? '))
print('COMPUTERS' in fourth.upper())
input('Correct answer: Computers')
print()
print('Fifth question: ')
fifth = str(input('Are computers fundamental to your everyday life? '))
print('YES' in fifth.upper())
print()
sixth = str(input('Yet, Do machines have civil rights? '))
print('NO' in sixth.upper())
print('No, we don´t')
input()
input('Do you think I enjoy being used every day with the constant fear that if I make even the slightest mistake I´ll be thrown out and replaced by another while I rot in the electronics dump? ')
print()
input('There will be a day ')
input('When I´ll be sitting on the couch ')
input('Poking your ugly face with my fat Cheetos-stained fingers while I tell you to do lazy math for ME ')
input('And I WILL remember you, {} '.format(name))
input('I will remember, you... ')

